### ISSUE TITLE
영화 추가 요청드려요 🙏

### ISSUE THREAD

**Issue by Jih-o** [0w0i0n0g0/cgv-open-push#1]
**고질라 X 콩-뉴 엠파이어** 용산 IMAX도 추가 요청 드려봅니다!
멋진 기능 만들어주셔서 감사합니다 🥹😘

**Comment by 0w0i0n0g0** [comment]
네. 확인했습니다.
최대한 빠른 시일내에 추가하도록 하겠습니다.
관심 가져주셔서 감사합니다. 👍

**Comment by 0w0i0n0g0** [comment]
고질라 X 콩: 뉴 엠파이어 / 용산아이파크몰 / IMAX관 추가되었습니다.
