### ISSUE TITLE
용산 영화 추가에 대한 문의드립니다🙏🙏🙏

### ISSUE THREAD

**Issue by stggfdd** [0w0i0n0g0/cgv-open-push#10]
용산 아이맥스 명탐정코난 극장판 백만달러의 펜타그램도 추가해주실 수 있을지 여쭤보고싶습니다🥹🙏

**Comment by 0w0i0n0g0** [comment]
네. 확인했습니다!
조만간 용아맥 명탐정코난-100만달러의펜타그램 알리미를 추가하도록 하겠습니다.
관심 가져주셔서 감사합니다 😄

**Comment by stggfdd** [comment]
감사합니다! 내일부터 무대인사가 오픈한다고 그래서 시간 여유가 있으시다면 최대한 빠른 시일내에 부탁드리고싶습니다..🥲 답변 감사드립니다!!

**Comment by 0w0i0n0g0** [comment]
용아맥 명탐정코난-100만달러의펜타그램이 추가되었습니다.

[https://github.com/0w0i0n0g0/cgv-open-push](https://github.com/0w0i0n0g0/cgv-open-push)의 **[알림 받는 방법!]** 에 따라서 알리미를 구독해주세요!
