### ISSUE TITLE
애프터썬 디깅타임 회차(09/04)

### ISSUE THREAD

**Issue by battlealbedo** [0w0i0n0g0/cgv-open-push#14]
https://gall.dcinside.com/mgallery/board/view/?id=oticket&no=1122307&page=1
용산 일반관이라 가능할까 또 널널할까 싶은데 굿즈있으니 예매알림 필요할거 같아 신청해봅니다;;

**Comment by battlealbedo** [comment]
> https://gall.dcinside.com/mgallery/board/view/?id=oticket&no=1122307&page=1
용산 일반관이라 가능할까 또 널널할까 싶은데 굿즈있으니 예매알림 필요할거 같아 신청해봅니다;;

**Comment by 0w0i0n0g0** [comment]
좋은 의견 감사드립니다.
다만, 특정 회차만에 해당하는 예매 오픈 알리미는 현재 알리미 동작 구조 상 힘들 것 같습니다.😢
많은 관심 감사드립니다.👍
