### ISSUE TITLE
혹시 왕십리 아이맥스 상영관도 추가 가능할까요?? 🥹

### ISSUE THREAD

**Issue by dune12** [0w0i0n0g0/cgv-open-push#15]
어플 유용하게 잘 쓰고있습니다!

혹시 왕십리 아이맥스 상영관 알림도 추가해주실 수 있나요??

추가해주신다면 감사하겠습니다!!

**Comment by 0w0i0n0g0** [comment]
네. 확인했습니다!
최대한 빠른 시일 내에 왕십리 IMAX 예매 오픈 알리미를 추가하도록 하겠습니다.
관심 가져주셔서 감사합니다 😄

**Comment by 0w0i0n0g0** [comment]
왕십리 IMAX 예매 오픈 알리미가 추가되었습니다.

[https://github.com/0w0i0n0g0/cgv-open-push](https://github.com/0w0i0n0g0/cgv-open-push)의 **[알림 받는 방법!]** 에 따라서 알리미를 구독해주세요!
