### ISSUE TITLE
앱 푸쉬 알림 및 노티 오류 문의

### ISSUE THREAD

**Issue by monstacha** [0w0i0n0g0/cgv-open-push#16]
![IMG_3054](https://github.com/user-attachments/assets/cdf984c8-0e0c-40b1-90df-7f4a11fc0995)
![IMG_3055](https://github.com/user-attachments/assets/99bb49ec-114d-42e7-abfc-add5afa715cb)
인녕하세요!
앱 푸쉬알림이 오기는 하는데
알림 내용 없이 new message라고만 뜨고
정작 앱에 들어가도 노티 목록에 새로운 알림이 안 뜨는 오류는 뭐가 문제일까요?

**Comment by 0w0i0n0g0** [comment]
해당 문제가 불특정하게 발생함을 인지하고 있으며, 이러한 문제는 알림을 위해 쓰는 ntfy 자체의 문제로 현재 해결이 불가한 것으로 보입니다.

따라서 최대한 빨리 **디스코드 알림 봇**으로도 사용할 수 있도록 업데이트 할 예정입니다.

그 전까지 해당 문제가 지속된다면, 꼭 알림이 필요한 한 구독만 남겨두고 해당 알림이 올 때 cgv 앱을 확인해 보는 방법으로 사용하실 수 있습니다.

관심 가져주셔서 감사합니다.

**Comment by 0w0i0n0g0** [comment]
디스코드 알리미가 새로 배포되었습니다! 

기존 ntfy 알림 서버는 12/01 부로 지원이 중단될 예정입니다. 

https://github.com/0w0i0n0g0/cgv-open-push 에서 CGV 예매 오픈 알리미 디스코드 서버에 접속할 수 있습니다.

감사합니다.
