### ISSUE TITLE
시험용 알림 발송이 안되는데 정상작동 중인 걸까요?

### ISSUE THREAD

**Issue by chaem1** [0w0i0n0g0/cgv-open-push#17]
안녕하세요, 최근에 폰을 바꾸면서 새로 깔게 되었는데
정상작동 하는지 테스트를 하고 싶어서 시험용 알림 발송을 눌렀더니 사진과 같은 멘트가 뜨며 오는 알림이 없어서 정상 작동 중인지 궁금하여 qa 남기게 되었습니다
감사합니다
![Screenshot_20241118_184149_ntfy](https://github.com/user-attachments/assets/fd4b317a-b0f1-420e-a769-47d41fc21134)

**Comment by aliexacc1** [comment]
안녕하세요!

테스트 메세지는 일반 사용자가 발송이 불가능한 것이 맞습니다.
알림은 영화 예매 오픈이 감지되었을 때만 서버에서 자동으로 관리자 권한으로 전송되는 방식으로,
일반 사용자가 테스트 메세지를 보내도 관리자 권한이 없어 거부됩니다.

감사합니다 :)

**Comment by 0w0i0n0g0** [comment]
안녕하세요!

테스트 메세지는 일반 사용자가 발송이 불가능한 것이 맞습니다.
알림은 영화 예매 오픈이 감지되었을 때만 서버에서 자동으로 관리자 권한으로 전송되는 방식으로,
일반 사용자가 테스트 메세지를 보내도 관리자 권한이 없어 거부됩니다.

감사합니다 :)
