### ISSUE TITLE
고질라 알림이 안 오는 것 같아 문의드려요

### ISSUE THREAD

**Issue by Jih-o** [0w0i0n0g0/cgv-open-push#2]
용산 아이맥스 관이 꽤 많이 열렸는데 알림 받은 게 없어서 그런데 확인 부탁드려요 😣🙏

**Comment by 0w0i0n0g0** [comment]
운영중인 서버가 당일 오전 9시에 다운되었는데 밖에 있어서 몇시간동안 재부팅을 못하던 중에 예매 오픈되어 알림이 안간 것으로 보입니다.

현재는 오류를 고쳤고 정상 작동중이며, 아래 링크에서 서버 작동 여부를 알 수 있습니다.

### http://serverkorea.duckdns.org:5000

감사합니다.
