### ISSUE TITLE
✨ 영화 추가 요청드려요!

### ISSUE THREAD

**Issue by Jih-o** [0w0i0n0g0/cgv-open-push#3]
**<극장판 하이큐!!! 쓰레기장의 결전>**
예매 알림 추가 부탁드려요 🫰

저 진짜 덕분에 듄 용아맥 잡았어요 ㅠㅠㅠ 감사함당 ❣️

**Comment by 0w0i0n0g0** [comment]
현재 영화 상관없이 작동할 수 있는 용아맥 예매 오픈 알리미를 제작 중에 있었지만, 
4월 말까지 시험기간으로, 유지보수 및 업데이트가 불가능한 상황입니다.
5월 초 다시 돌아오도록 하겠습니다.
항상 많은 관심 가져주셔서 감사합니다. 👍

**Comment by 0w0i0n0g0** [comment]
**극장판하이큐!!쓰레기장의결전 / 용산아이파크몰 / IMAX 관**
추가 완료되었습니다.

다만 현재 CGV의 서버 쪽 제한으로 인하여, 기존 **5초**마다 갱신하던 것을 **5분**으로 늘렸습니다.
이로 인해 최대 5분 간의 알림 지연이 생길 수 있으니 양해 부탁드립니다.
감사합니다.
