### ISSUE TITLE
영화 추가 요청부탁드립니다! 🙏

### ISSUE THREAD

**Issue by dune12** [0w0i0n0g0/cgv-open-push#4]
안녕하세요!! 알.리미 항상 감사히 잘 쓰고있습니다!

혹시 괜찮다면 <혹성탈출: 새로운 시대>와 <퓨리오사: 매드맥스 사가>도 추가 가능할까요??

**Comment by 0w0i0n0g0** [comment]
**혹성탈출-새로운시대 / 용산아이파크몰 / IMAX 관** 추가 완료하였습니다.
밑의 사진처럼 등록하시면 됩니다.
<p align="center">
  <img src="https://github.com/0w0i0n0g0/cgv-open-push/assets/83498372/ce277a45-7e58-43c0-83d3-e2c2923c825d" width="300"/>
</p>
README에는 내일 중 업데이트 하도록 하겠습니다.



또한 **퓨리오사:매드맥스사가**에 대해서는 CGV 서버에 해당 영화가 등록되는대로 추가하도록 하겠습니다.
**퓨리오사:매드맥스사가** 1주차 오픈은 [구독 리스트의 1번](https://github.com/0w0i0n0g0/cgv-open-push?tab=readme-ov-file#%EA%B5%AC%EB%8F%85-%EB%A6%AC%EC%8A%A4%ED%8A%B8)의 용아맥 예매 오픈 알리미 (베타)를 사용해주세요.

감사합니다.
