### ISSUE TITLE
[신작요청]안녕하세요. 퓨리오사 추가 가능한가요!?

### ISSUE THREAD

**Issue by allnoodle** [0w0i0n0g0/cgv-open-push#5]
지금 통합 IMAX 서버도 쓰고 있긴한데 혹시 퓨리오사 추가가 가능하시면 요청드립니다!
1주차는 어제 열린 것 같더라구요~!

**Comment by 0w0i0n0g0** [comment]
용산아이파크몰 IMAX관 **퓨리오사-매드맥스사가** 추가 완료되었습니다.
업데이트된 [구독 리스트](https://github.com/0w0i0n0g0/cgv-open-push?tab=readme-ov-file#%EA%B5%AC%EB%8F%85-%EB%A6%AC%EC%8A%A4%ED%8A%B8)를 확인해주세요!
