### ISSUE TITLE
알림이 오지 않습니다 ...!

### ISSUE THREAD

**Issue by ZZUNEE** [0w0i0n0g0/cgv-open-push#6]
서버에는 분명 로그가 있는데 알림이 하나도 오지 않습니다.
테스트 메세지를 보내봐도 오질 않네요...
뭐가 문제일까요?ㅠㅠ

**Comment by ZZUNEE** [comment]
그리고 혹시 울포디도 같이 알림이 제공되는 걸까요?

**Comment by 0w0i0n0g0** [comment]
어떤 로그를 말씀하시는 것인지 알 수가 없어, 해당 로그를 여기에 올려주시면 확인해보도록 하겠습니다.

혹시 어떤 영화가 언제 예매 오픈 되었을 때 알림을 못 받은 것일까요?

또한 테스트 메세지는 일반 사용자가 발송이 불가능한 것이 맞습니다. 
알림은 영화 예매 오픈이 감지되었을 때만 서버에서 자동으로 관리자 권한으로 전송되는 방식으로, 
일반 사용자가 테스트 메세지를 보내도 관리자 권한이 없어 거부됩니다.

마지막으로 용산아이파크몰 4DX관은 아직 알림이 제공되고 있지 않습니다.
좋은 의견 감사드리며 해당 기능도 추가하도록 하겠습니다.

더 궁금하신 점 여기에 적여주시면 최대한 빠르게 답변해드리도록 하겠습니다.

**Comment by ZZUNEE** [comment]
서버 로그는 http://serverkorea.duckdns.org:5000/ 여기에 나온 로그들을 말씀드렸던 겁니다!

이틀차인 어제까지는 알림이 오지 않았는데 오늘부터 작동이 잘 되네요...!
세팅을 처음부터 완전 다시 했는데, 초기 세팅 시 뭔가 오류가 있었나 봅니다.

퓨리오사 용산 울포디 알림도 가능할까요?
4dx관 추가를 기다리며 좋은 서비스 제공해 주셔서 감사하단 말씀 전합니다.
감사합니다!
