### ISSUE TITLE
다른 지점 알림도 가능한가요?

### ISSUE THREAD

**Issue by tong3k** [0w0i0n0g0/cgv-open-push#7]
부산 서면점도 확인하고 싶은데 가능할까요?

**Comment by 0w0i0n0g0** [comment]
네. 특정 영화관의 특정 상영관으로 특정해주시면 추가할 수 있습니다.
부산 서면 CGV IMAX관 이런 식으로 추가할 수 있습니다.

**Comment by tong3k** [comment]
부산 서면 CGV IMAX

염치 없지만 추가 부탁 드려도 될까요?

2024년 7월 9일 (화) 오후 10:00, 0w0i0n0g0 ***@***.***>님이 작성:

**Comment by 0w0i0n0g0** [comment]
조만간 서면 CGV IMAX관 알리미를 추가하도록 하겠습니다.
관심 가져주셔서 감사합니다 😄

**Comment by 0w0i0n0g0** [comment]
서면 IMAX 예매 오픈 알리미가 추가되었습니다.

[https://github.com/0w0i0n0g0/cgv-open-push](https://github.com/0w0i0n0g0/cgv-open-push)의 **[알림 받는 방법!]** 에 따라서 알리미를 구독해주세요!

**Comment by tong3k** [comment]
7월 15일 이후 알람이 오지 않습니다.
최근 서면CGV IMAX 관 수리로 닫혀있었는데 변경 부분이 있는게 아닌가 싶습니다.
