### ISSUE TITLE
용산 아이맥스 알리미 않됩니다

### ISSUE THREAD

**Issue by Three2seven** [0w0i0n0g0/cgv-open-push#8]
![IMG_8298](https://github.com/user-attachments/assets/9a75ab5b-a2ca-4c8c-a288-2fde1a65094e)
![IMG_8299](https://github.com/user-attachments/assets/e9915f87-2bf6-48ad-a98d-c010cff9784f)
![IMG_8300](https://github.com/user-attachments/assets/6d3f614d-5aa2-41c3-a558-7081f4e6e32b)
설정은 맞게 한거 같든데 4dx 만 알림이 옵니다

**Comment by 0w0i0n0g0** [comment]
혹시 최초 알림 등록일이 언제일까요?
현재 용아맥 예매 오픈 알리미의 마지막 알림 전송 일자는 7월 11일입니다.
7월 11일 알림 전송 이후에 알리미를 등록하셨다면 아직 알림이 안오는 것이 정상으로 보여집니다.

추후에 용아맥 오픈 알리미에 알림이 온다면 이 곳에 알려드려서 확인하실 수 있도록 하겠습니다.
알림이 오지 않는다면 더 정확하게 확인하도록 하겠습니다.

**Comment by 0w0i0n0g0** [comment]
오늘 오전 10:46, 10:51에 예매 오픈 알림이 전송된 것으로 확인됩니다.
알림이 오지 않았다면 다시 issue에 글을 남겨주세요!
