### ISSUE TITLE
혹시 괜찮다면 영등포 아이맥스도 추가해주실 수 있을까요?🙏

### ISSUE THREAD

**Issue by dune12** [0w0i0n0g0/cgv-open-push#9]
영아맥 알리미도 추가해주신다면 정말 감사드리겠습니다!!

**Comment by 0w0i0n0g0** [comment]
네. 확인했습니다!
조만간 영등포 CGV IMAX관 알리미를 추가하도록 하겠습니다.
관심 가져주셔서 감사합니다 😄

**Comment by 0w0i0n0g0** [comment]
영등포 IMAX 예매 오픈 알리미가 추가되었습니다.

[https://github.com/0w0i0n0g0/cgv-open-push](https://github.com/0w0i0n0g0/cgv-open-push)의 **[알림 받는 방법!]** 에 따라서 알리미를 구독해주세요!

**Comment by dune12** [comment]
감사합니다°
